apiVersion: v1
kind: Template
metadata:
  name: cogwheel
  annotations:
  labels:
    name: cogwheel
objects:
 - apiVersion: batch/v1
   kind: Job
   metadata:
     name: cogwheel
     annotations:
     labels:
       name: cogwheel
   spec:
     parallelism: 1
     completions: 1
     backoffLimit: 0
     template:
       metadata:
         name: cogwheel
       spec:
         containers:
         - name: cogwheel
           image: "${WORKLOAD_IMAGE}"
           imagePullPolicy: Always
           envFrom:
           - configMapRef:
               name: workload-config
           env:
             - name: kubeconfig
               valueFrom:
                 configMapKeyRef:
                   name: kube-config
                   key: kubeconfig
         restartPolicy: Never 
parameters:
- description: image used to run the scale test
  name: WORKLOAD_IMAGE
  required: true
labels:
  name: cogwheel
